# Generated by Django 4.0.2 on 2022-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('tal_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('tal_descripcion', models.CharField(max_length=30)),
                ('tal_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'talla',
            },
        ),
    ]
