# Generated by Django 4.0.2 on 2022-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TALLA',
            fields=[
                ('TAL_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('TAL_DESCRIPCION', models.CharField(max_length=50)),
                ('TAL_ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'db_table': 'talla',
            },
        ),
    ]
