# Generated by Django 4.0.2 on 2022-05-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('prod_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('prod_precio_compra_base', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de compra base')),
                ('prod_precio_compra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de compra')),
                ('prod_precio_venta_base', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de venta base')),
                ('prod_precio_venta', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio de venta')),
                ('prod_descuento_promocion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento o promoción')),
                ('proveedor', models.IntegerField(verbose_name='Proveedor')),
                ('categoria', models.IntegerField(verbose_name='Categoría')),
                ('marca', models.IntegerField(verbose_name='Marca')),
                ('modelo', models.IntegerField(verbose_name='Modelo')),
                ('color', models.IntegerField(verbose_name='Color')),
                ('talla', models.IntegerField(verbose_name='Talla')),
                ('prod_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
