# Generated by Django 4.0 on 2022-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MARCAS',
            fields=[
                ('MAR_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='MAR_ID')),
                ('MAR_DESCRIPCION', models.CharField(max_length=50)),
                ('SUC_ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marca',
                'ordering': ['MAR_ID'],
            },
        ),
    ]
