# Generated by Django 4.0 on 2022-02-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='SUC_ESTADO',
            new_name='MAR_ESTADO',
        ),
    ]
