# Generated by Django 4.0.2 on 2022-04-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0002_rename_mar_descripcion_marca_mar_descripcione_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='mar_id',
            new_name='mar_ide',
        ),
    ]
