# Generated by Django 4.0.2 on 2022-07-06 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('tiendas', '0002_remove_tienda_sucursal_tienda_tie_suc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDeIngreso',
            fields=[
                ('nota_ingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota_ingreso_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha registro')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='compras.compra')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tienda', to='tiendas.tienda')),
            ],
            options={
                'verbose_name': 'Nota de Ingreso',
                'verbose_name_plural': 'Notas de Ingreso',
                'db_table': 'nota_de_ingreso',
            },
        ),
    ]
