# Generated by Django 4.0.2 on 2022-05-23 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaDeRemision',
            fields=[
                ('guia_id', models.AutoField(primary_key=True, serialize=False)),
                ('guia_serie', models.CharField(max_length=4, verbose_name='Nro. serie')),
                ('guia_numero', models.CharField(max_length=8, verbose_name='Nro. guía')),
                ('guia_fecha', models.DateField(verbose_name='Fecha guía remisión')),
                ('guia_flete', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Flete')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia_compra', to='compras.compra')),
            ],
            options={
                'verbose_name': 'Guía de remisión',
                'verbose_name_plural': 'Guías de remisión',
                'db_table': 'guia_de_remision',
            },
        ),
    ]
