# Generated by Django 4.0.2 on 2022-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('mod_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('mod_descripcion', models.CharField(max_length=50)),
                ('mod_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
            },
        ),
    ]
