# Generated by Django 4.0.2 on 2022-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MODELO',
            fields=[
                ('MOD_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('MOD_DESCRIPCION', models.CharField(max_length=50)),
                ('MOD_ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
            },
        ),
    ]
