# Generated by Django 4.0.2 on 2022-05-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_monto_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto total')),
                ('comp_fecha_registro', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha registro')),
                ('usuario', models.IntegerField(verbose_name='Usuario')),
                ('proveedor', models.IntegerField(verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
    ]
