# Generated by Django 4.0.2 on 2022-05-19 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comp_fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha registro'),
        ),
    ]
