# Generated by Django 4.0.2 on 2022-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comp_importe_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total'),
        ),
    ]
