# Generated by Django 4.0 on 2022-02-07 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIENDAS',
            fields=[
                ('TIE_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='TIE_ID')),
                ('TIE_NOMBRE', models.CharField(max_length=50)),
                ('TIE_ESTADO', models.BooleanField(default=True)),
                ('TIE_SUC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursales', verbose_name='TIE_SUC_ID')),
            ],
            options={
                'db_table': 'tienda',
                'ordering': ['TIE_ID'],
            },
        ),
    ]
