# Generated by Django 4.0.2 on 2022-05-08 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='tienda',
            name='tie_suc_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='sucursales.sucursal'),
            preserve_default=False,
        ),
    ]
