# Generated by Django 4.0 on 2022-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PROVEEDORES',
            fields=[
                ('PRO_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='PRO_ID')),
                ('PRO_RUC', models.CharField(max_length=11)),
                ('PRO_NOMBRE', models.CharField(max_length=50)),
                ('PRO_EMAIL', models.EmailField(max_length=50)),
                ('SUC_TELEFONO1', models.CharField(max_length=12)),
                ('SUC_TELEFONO2', models.CharField(max_length=12)),
                ('SUC_DIRECCION1', models.CharField(max_length=50)),
                ('SUC_DIRECCION2', models.CharField(max_length=50)),
                ('SUC_ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ['PRO_ID'],
            },
        ),
    ]
