# Generated by Django 4.0.2 on 2022-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False, verbose_name='pro_id')),
                ('pro_ruc', models.CharField(max_length=11)),
                ('pro_nombre', models.CharField(max_length=50)),
                ('pro_email', models.EmailField(max_length=50)),
                ('pro_telefono1', models.CharField(max_length=12)),
                ('pro_telefono2', models.CharField(max_length=12)),
                ('pro_direccion1', models.CharField(max_length=50)),
                ('pro_direccion2', models.CharField(max_length=50)),
                ('pro_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
    ]
