# Generated by Django 4.0.2 on 2022-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='pro_razon_social',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
