# Generated by Django 4.0.2 on 2022-05-23 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDeCompra',
            fields=[
                ('det_comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('det_comp_cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('det_comp_importe', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto detalle')),
                ('producto', models.IntegerField(verbose_name='Producto')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra', to='compras.compra')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
                'db_table': 'detalle_de_compra',
            },
        ),
    ]
