# Generated by Django 4.0.2 on 2022-05-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_de_compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalledecompra',
            table='detalle_de_compra',
        ),
    ]
