# Generated by Django 4.0.2 on 2022-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDeIngreso',
            fields=[
                ('det_ingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('det_ingreso_cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso',
                'verbose_name_plural': 'Detalles de Ingreso',
                'db_table': 'detalle_de_ingreso',
            },
        ),
    ]
