# Generated by Django 4.0.2 on 2022-04-17 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('est_civil_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Estado Civil ID')),
                ('est_civil_descripcion', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('info_per_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Inf. Personal Nº')),
                ('info_per_nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres')),
                ('info_per_apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos')),
                ('info_per_email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email')),
                ('info_per_genero', models.CharField(default='F', max_length=1, verbose_name='Género')),
                ('info_per_fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('info_per_direc_1', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección 1')),
                ('info_per_direc_2', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección 2')),
                ('info_per_cel_1', models.CharField(blank=True, max_length=9, null=True, verbose_name='Nro. Celular 1')),
                ('info_per_cel_2', models.CharField(blank=True, max_length=9, null=True, verbose_name='Nro. Celular 2')),
                ('usuario', models.IntegerField(unique=True, verbose_name='Usuario')),
                ('estado_civil', models.IntegerField(unique=True, verbose_name='Estado Civil')),
                ('tipo_documento', models.IntegerField(unique=True, verbose_name='Tipo de documento')),
                ('info_per_nro_doc', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nro. Documento')),
            ],
            options={
                'verbose_name': 'Información Personal',
                'verbose_name_plural': 'Informaciones personales',
                'db_table': 'informacion_personal',
            },
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('tipo_doc_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Tipo de documento - ID')),
                ('tipo_doc_descripcion', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo documento personal',
                'verbose_name_plural': 'Tipos de documentos personales',
                'db_table': 'tipo_documento_personal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_employee', models.BooleanField(default=True, verbose_name='Empleado')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super Usuario')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha creación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
