# Generated by Django 4.0.2 on 2022-02-11 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estadocivil_tipodocumento_informacionpersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpersonal',
            name='ESTADO_CIVIL_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.estadocivil', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_APELLIDOS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_CELULAR1',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Nro. Celular 1'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_CELULAR2',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Nro. Celular 2'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_DIRECCION1',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección 1'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_DIRECCION2',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección 2'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_DOCUMENTO_IDENTIDAD',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nro. Documento'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_EMAIL',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_FECHA_NACIMIENTO',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_GENERO',
            field=models.CharField(default='F', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='INFO_PER_NOMBRES',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='TIPO_DOC_PER_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='USU_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_employee',
            field=models.BooleanField(default=True, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
