# Generated by Django 4.0.2 on 2022-02-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_informacionpersonal_estado_civil_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='USU_ID',
            new_name='USUARIO',
        ),
    ]
