# Generated by Django 4.0.2 on 2022-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_usu_id_informacionpersonal_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDocumento',
            new_name='TipoDeDocumento',
        ),
        migrations.RenameField(
            model_name='tipodedocumento',
            old_name='TIPO_DOC_PER_DESCRIPCION',
            new_name='tipo_doc_descripcion',
        ),
        migrations.RenameField(
            model_name='tipodedocumento',
            old_name='TIPO_DOC_PER_ID',
            new_name='tipo_doc_id',
        ),
    ]
