# Generated by Django 4.0.2 on 2022-03-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_tipodocumento_tipodedocumento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocivil',
            old_name='ESTADO_CIVIL_DESCRIPCION',
            new_name='est_civil_descripcion',
        ),
        migrations.RenameField(
            model_name='estadocivil',
            old_name='ESTADO_CIVIL_ID',
            new_name='est_civil_id',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='ESTADO_CIVIL_ID',
            new_name='estado_civil',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_APELLIDOS',
            new_name='info_per_apellidos',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_CELULAR1',
            new_name='info_per_cel_1',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_CELULAR2',
            new_name='info_per_cel_2',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_DIRECCION1',
            new_name='info_per_direc_1',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_DIRECCION2',
            new_name='info_per_direc_2',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_EMAIL',
            new_name='info_per_email',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_FECHA_NACIMIENTO',
            new_name='info_per_fecha_nac',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_GENERO',
            new_name='info_per_genero',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_ID',
            new_name='info_per_id',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_NOMBRES',
            new_name='info_per_nombres',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='INFO_PER_DOCUMENTO_IDENTIDAD',
            new_name='info_per_nro_doc',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='TIPO_DOC_PER_ID',
            new_name='tipo_documento',
        ),
        migrations.RenameField(
            model_name='informacionpersonal',
            old_name='USUARIO',
            new_name='usuario',
        ),
    ]
