# Generated by Django 4.0.2 on 2022-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COLOR',
            fields=[
                ('COL_ID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('COL_DESCRIPCION', models.CharField(max_length=50)),
                ('COL_ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'color',
            },
        ),
    ]
