# Generated by Django 4.0.2 on 2022-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('col_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('col_descripcion', models.CharField(max_length=30)),
                ('col_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'db_table': 'color',
            },
        ),
    ]
