# Generated by Django 4.0.2 on 2022-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cat_descripcion', models.CharField(max_length=30)),
                ('cat_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
    ]
