# Generated by Django 4.0.2 on 2022-02-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='cat_descripcion',
            new_name='CAT_DESCRIPCION',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='cat_estado',
            new_name='CAT_ESTADO',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='cat_id',
            new_name='CAT_ID',
        ),
    ]
