# Generated by Django 4.0.2 on 2022-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_cat_descripcion_categoria_cat_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='CAT_ESTADO',
            new_name='cat_estado',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='CAT_ID',
            new_name='cat_id',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='CAT_DESCRIPCION',
        ),
        migrations.AddField(
            model_name='categoria',
            name='cat_descripcion',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
